### PR TITLE
Updating styling branch 

### PR DESCRIPTION
**Pull request by DXCanas**
Just keeping styling up to date

### CODE REVIEW

**Comment by DXCanas** [comment]
@indirectlylit You said we probably don't want this to happen? Should have closed it right then.

sorry @christianmemije.

**Comment by christianmemije** [comment]
@DXCanas :coffin: You can revert this!

**Comment by christianmemije** [comment]
Nice `revert` button up there ^

**Comment by DXCanas** [comment]
just wanna confirm with @indirectlylit before i do @christianmemije

**Comment by indirectlylit** [comment]
worth a try

I've had mixed results with the 'revert' button. if you run into issues, just delete and recreate the styling branch

**Comment by indirectlylit** [comment]
but yes, styling should be based on vanilla kolibri, not VF

**Pull request merged**
