### PR TITLE
Fix Distorted Logos

### PR DESCRIPTION
**Pull request by christianmemije**
## Summary

Fix Distorted Logos

## Issue Addressed

https://github.com/learningequality/kolibri/issues/983

### CODE REVIEW

**Comment by christianmemije** [comment]
Can't seem to be able to upload images to GIthub right now...

**Comment by indirectlylit** [comment]
yeah I'm having the same problem

On Tue, Feb 28, 2017 at 12:01 PM, Christian Memije <notifications@github.com

**Comment by christianmemije** [comment]
## Before

bs_win8_ie_10 0 3

bs_win8_ie_10 0 4

 ## After

bs_win8_ie_10 0 6

bs_win8_ie_10 0 5

**Comment by rtibbles** [comment]
Are these the right screenshots? Because they look very un instant schools to me.

**Comment by christianmemije** [comment]
Updated Screenshots @rtibbles 
## Before
bs_win8_ie_10 0 11
bs_win8_ie_10 0 12
## After
bs_win8_ie_10 0 9
bs_win8_ie_10 0 10

**Pull request merged**
