### PR TITLE
Add icon to app bar

### PR DESCRIPTION
**Pull request by christianmemije**
Adresses #57  
Depends on https://github.com/learningequality/kolibri/pull/2487

image

### CODE REVIEW

**Comment by DXCanas** [comment]
I've been thinking about the consequences of swapping the core logo for the instant schools one, moving core's to another prop - you think this would be a bad idea? might make it easier to whitelabel later

**Comment by rtibbles** [comment]
I think the way that @christianmemije has enabled it by making it a configurable variable for the background does the same. I guess one question is whether it throws any errors when it is undefined?

**Comment by christianmemije** [comment]
When undefined, the css values are invalid so the div has no height/width 

image

**Comment by christianmemije** [comment]
We could add the variables to the core theme style sheet and just give them dummy values, but that is unnecessary.

**Comment by rtibbles** [comment]
Great.

**Comment by DXCanas** [comment]
I think it might even be worth to make it more generic - as I mentioned in this comment: https://github.com/learningequality/kolibri/pull/2487#issuecomment-338322798

Seems we're going to be using the vf logo in a couple places?

**Comment by christianmemije** [comment]
@DXCanas Where else outside of this plugin, besides the app-bar, would we need to display a VF logo?

**Comment by DXCanas** [comment]
sign in

sign up uses an app-bar, but it's not the same one we're using here

**Pull request merged**
